
##### 

#start powershell "..\bin\test.exe  -c  D:/Projects/data/cfg_VTM4_0/encoder_lowdelay_P_vtm.cfg -c  D:/Projects/data/cfg_VTM4_0/per-sequence/BasketballPass.cfg -i D:/Projects/data/test_seq/HEVC/BasketballPass_416x240_50.yuv --PrintFrameMSE=1 -f 1 -q 22 -qpa 1 -fs 1 --ALF=0 --SAO=0 --LoopFilterDisable=1 -c  D:\Projects\date\20191223\code\encoder_ldpnh_vtm.cfg  --IntraQPOffset=0 | tee ./test/ClassD_BasketballPass_416x240_50_22_LDP.txt"
#start powershell "..\bin\test.exe  -c  D:/Projects/data/cfg_VTM4_0/encoder_lowdelay_P_vtm.cfg -c  D:/Projects/data/cfg_VTM4_0/per-sequence/BasketballPass.cfg -i D:/Projects/data/test_seq/HEVC/BasketballPass_416x240_50.yuv --PrintFrameMSE=1 -f 1 -q 27 -qpa 1 -fs 1 --ALF=0 --SAO=0 --LoopFilterDisable=1 -c  D:\Projects\date\20191223\code\encoder_ldpnh_vtm.cfg  --IntraQPOffset=0 | tee ./test/ClassD_BasketballPass_416x240_50_27_LDP.txt"
#start powershell "..\bin\test.exe  -c  D:/Projects/data/cfg_VTM4_0/encoder_lowdelay_P_vtm.cfg -c  D:/Projects/data/cfg_VTM4_0/per-sequence/BasketballPass.cfg -i D:/Projects/data/test_seq/HEVC/BasketballPass_416x240_50.yuv --PrintFrameMSE=1 -f 1 -q 32 -qpa 1 -fs 1 --ALF=0 --SAO=0 --LoopFilterDisable=1 -c  D:\Projects\date\20191223\code\encoder_ldpnh_vtm.cfg  --IntraQPOffset=0 | tee ./test/ClassD_BasketballPass_416x240_50_32_LDP.txt"
#start powershell "..\bin\test.exe  -c  D:/Projects/data/cfg_VTM4_0/encoder_lowdelay_P_vtm.cfg -c  D:/Projects/data/cfg_VTM4_0/per-sequence/BasketballPass.cfg -i D:/Projects/data/test_seq/HEVC/BasketballPass_416x240_50.yuv --PrintFrameMSE=1 -f 1 -q 37 -qpa 1 -fs 1 --ALF=0 --SAO=0 --LoopFilterDisable=1 -c  D:\Projects\date\20191223\code\encoder_ldpnh_vtm.cfg  --IntraQPOffset=0 | tee ./test/ClassD_BasketballPass_416x240_50_37_LDP.txt"


#start powershell "..\bin\ref.exe  -c  D:/Projects/data/cfg_VTM4_0/encoder_lowdelay_P_vtm.cfg -c  D:/Projects/data/cfg_VTM4_0/per-sequence/BasketballPass.cfg -i D:/Projects/data/test_seq/HEVC/BasketballPass_416x240_50.yuv --PrintFrameMSE=1 -f 1 -q 22 -fs 1 --ALF=0 --SAO=0 --LoopFilterDisable=1 -c  D:\Projects\date\20191223\code\encoder_ldpnh_vtm.cfg  --IntraQPOffset=0 | tee ./ref/ClassD_BasketballPass_416x240_50_22_LDP.txt"
#start powershell "..\bin\ref.exe  -c  D:/Projects/data/cfg_VTM4_0/encoder_lowdelay_P_vtm.cfg -c  D:/Projects/data/cfg_VTM4_0/per-sequence/BasketballPass.cfg -i D:/Projects/data/test_seq/HEVC/BasketballPass_416x240_50.yuv --PrintFrameMSE=1 -f 1 -q 27 -fs 1 --ALF=0 --SAO=0 --LoopFilterDisable=1 -c  D:\Projects\date\20191223\code\encoder_ldpnh_vtm.cfg  --IntraQPOffset=0 | tee ./ref/ClassD_BasketballPass_416x240_50_27_LDP.txt"
#start powershell "..\bin\ref.exe  -c  D:/Projects/data/cfg_VTM4_0/encoder_lowdelay_P_vtm.cfg -c  D:/Projects/data/cfg_VTM4_0/per-sequence/BasketballPass.cfg -i D:/Projects/data/test_seq/HEVC/BasketballPass_416x240_50.yuv --PrintFrameMSE=1 -f 1 -q 32 -fs 1 --ALF=0 --SAO=0 --LoopFilterDisable=1 -c  D:\Projects\date\20191223\code\encoder_ldpnh_vtm.cfg  --IntraQPOffset=0 | tee ./ref/ClassD_BasketballPass_416x240_50_32_LDP.txt"
#start powershell "..\bin\ref.exe  -c  D:/Projects/data/cfg_VTM4_0/encoder_lowdelay_P_vtm.cfg -c  D:/Projects/data/cfg_VTM4_0/per-sequence/BasketballPass.cfg -i D:/Projects/data/test_seq/HEVC/BasketballPass_416x240_50.yuv --PrintFrameMSE=1 -f 1 -q 37 -fs 1 --ALF=0 --SAO=0 --LoopFilterDisable=1 -c  D:\Projects\date\20191223\code\encoder_ldpnh_vtm.cfg  --IntraQPOffset=0 | tee ./ref/ClassD_BasketballPass_416x240_50_37_LDP.txt"

#####

#start powershell "..\bin\test.exe  -c  D:/Projects/data/cfg_VTM4_0/encoder_intra_vtm.cfg -c  D:/Projects/data/cfg_VTM4_0/per-sequence/BasketballPass.cfg -i D:/Projects/data/test_seq/HEVC/BasketballPass_416x240_50.yuv --PrintFrameMSE=1 -f 1 -q 22 -qpa 1 -fs 1  --ALF=0 --SAO=0 --LoopFilterDisable=1 | tee ./test/ClassD_BasketballPass_416x240_50_22_AI.txt"
#start powershell "..\bin\test.exe  -c  D:/Projects/data/cfg_VTM4_0/encoder_intra_vtm.cfg -c  D:/Projects/data/cfg_VTM4_0/per-sequence/BasketballPass.cfg -i D:/Projects/data/test_seq/HEVC/BasketballPass_416x240_50.yuv --PrintFrameMSE=1 -f 1 -q 27 -qpa 1 -fs 1  --ALF=0 --SAO=0 --LoopFilterDisable=1 | tee ./test/ClassD_BasketballPass_416x240_50_27_AI.txt"
#start powershell "..\bin\test.exe  -c  D:/Projects/data/cfg_VTM4_0/encoder_intra_vtm.cfg -c  D:/Projects/data/cfg_VTM4_0/per-sequence/BasketballPass.cfg -i D:/Projects/data/test_seq/HEVC/BasketballPass_416x240_50.yuv --PrintFrameMSE=1 -f 1 -q 32 -qpa 1 -fs 1  --ALF=0 --SAO=0 --LoopFilterDisable=1 | tee ./test/ClassD_BasketballPass_416x240_50_32_AI.txt"
#start powershell "..\bin\test.exe  -c  D:/Projects/data/cfg_VTM4_0/encoder_intra_vtm.cfg -c  D:/Projects/data/cfg_VTM4_0/per-sequence/BasketballPass.cfg -i D:/Projects/data/test_seq/HEVC/BasketballPass_416x240_50.yuv --PrintFrameMSE=1 -f 1 -q 37 -qpa 1 -fs 1  --ALF=0 --SAO=0 --LoopFilterDisable=1 | tee ./test/ClassD_BasketballPass_416x240_50_37_AI.txt"


#start powershell "..\bin\ref.exe  -c  D:/Projects/data/cfg_VTM4_0/encoder_intra_vtm.cfg -c  D:/Projects/data/cfg_VTM4_0/per-sequence/BasketballPass.cfg -i D:/Projects/data/test_seq/HEVC/BasketballPass_416x240_50.yuv --PrintFrameMSE=1 -f 1 -q 22 -fs 1 --ALF=0 --SAO=0 --LoopFilterDisable=1 | tee ./ref/ClassD_BasketballPass_416x240_50_22_AI.txt"
#start powershell "..\bin\ref.exe  -c  D:/Projects/data/cfg_VTM4_0/encoder_intra_vtm.cfg -c  D:/Projects/data/cfg_VTM4_0/per-sequence/BasketballPass.cfg -i D:/Projects/data/test_seq/HEVC/BasketballPass_416x240_50.yuv --PrintFrameMSE=1 -f 1 -q 27 -fs 1 --ALF=0 --SAO=0 --LoopFilterDisable=1 | tee ./ref/ClassD_BasketballPass_416x240_50_27_AI.txt"
#start powershell "..\bin\ref.exe  -c  D:/Projects/data/cfg_VTM4_0/encoder_intra_vtm.cfg -c  D:/Projects/data/cfg_VTM4_0/per-sequence/BasketballPass.cfg -i D:/Projects/data/test_seq/HEVC/BasketballPass_416x240_50.yuv --PrintFrameMSE=1 -f 1 -q 32 -fs 1 --ALF=0 --SAO=0 --LoopFilterDisable=1 | tee ./ref/ClassD_BasketballPass_416x240_50_32_AI.txt"
#start powershell "..\bin\ref.exe  -c  D:/Projects/data/cfg_VTM4_0/encoder_intra_vtm.cfg -c  D:/Projects/data/cfg_VTM4_0/per-sequence/BasketballPass.cfg -i D:/Projects/data/test_seq/HEVC/BasketballPass_416x240_50.yuv --PrintFrameMSE=1 -f 1 -q 37 -fs 1 --ALF=0 --SAO=0 --LoopFilterDisable=1 | tee ./ref/ClassD_BasketballPass_416x240_50_37_AI.txt"

##### 

start powershell "..\bin\test.exe  -c  D:/Projects/data/cfg_VTM4_0/encoder_randomaccess_vtm.cfg -c  D:/Projects/data/cfg_VTM4_0/per-sequence/BasketballPass.cfg -i D:/Projects/data/test_seq/HEVC/BasketballPass_416x240_50.yuv --PrintFrameMSE=1 -f 33 -q 22 -ip 48 -qpa 1  | tee ./test/ClassD_BasketballPass_416x240_50_22_RA.txt"
start powershell "..\bin\test.exe  -c  D:/Projects/data/cfg_VTM4_0/encoder_randomaccess_vtm.cfg -c  D:/Projects/data/cfg_VTM4_0/per-sequence/BasketballPass.cfg -i D:/Projects/data/test_seq/HEVC/BasketballPass_416x240_50.yuv --PrintFrameMSE=1 -f 33 -q 27 -ip 48 -qpa 1  | tee ./test/ClassD_BasketballPass_416x240_50_27_RA.txt"
start powershell "..\bin\test.exe  -c  D:/Projects/data/cfg_VTM4_0/encoder_randomaccess_vtm.cfg -c  D:/Projects/data/cfg_VTM4_0/per-sequence/BasketballPass.cfg -i D:/Projects/data/test_seq/HEVC/BasketballPass_416x240_50.yuv --PrintFrameMSE=1 -f 33 -q 32 -ip 48 -qpa 1  | tee ./test/ClassD_BasketballPass_416x240_50_32_RA.txt"
start powershell "..\bin\test.exe  -c  D:/Projects/data/cfg_VTM4_0/encoder_randomaccess_vtm.cfg -c  D:/Projects/data/cfg_VTM4_0/per-sequence/BasketballPass.cfg -i D:/Projects/data/test_seq/HEVC/BasketballPass_416x240_50.yuv --PrintFrameMSE=1 -f 33 -q 37 -ip 48 -qpa 1  | tee ./test/ClassD_BasketballPass_416x240_50_37_RA.txt"


#start powershell "..\bin\ref.exe  -c  D:/Projects/data/cfg_VTM4_0/encoder_randomaccess_vtm.cfg -c  D:/Projects/data/cfg_VTM4_0/per-sequence/BasketballPass.cfg -i D:/Projects/data/test_seq/HEVC/BasketballPass_416x240_50.yuv --PrintFrameMSE=1 -f 33 -q 22  -ip 48    | tee ./ref/ClassD_BasketballPass_416x240_50_22_RA.txt"
#start powershell "..\bin\ref.exe  -c  D:/Projects/data/cfg_VTM4_0/encoder_randomaccess_vtm.cfg -c  D:/Projects/data/cfg_VTM4_0/per-sequence/BasketballPass.cfg -i D:/Projects/data/test_seq/HEVC/BasketballPass_416x240_50.yuv --PrintFrameMSE=1 -f 33 -q 27  -ip 48    | tee ./ref/ClassD_BasketballPass_416x240_50_27_RA.txt"
#start powershell "..\bin\ref.exe  -c  D:/Projects/data/cfg_VTM4_0/encoder_randomaccess_vtm.cfg -c  D:/Projects/data/cfg_VTM4_0/per-sequence/BasketballPass.cfg -i D:/Projects/data/test_seq/HEVC/BasketballPass_416x240_50.yuv --PrintFrameMSE=1 -f 33 -q 32  -ip 48    | tee ./ref/ClassD_BasketballPass_416x240_50_32_RA.txt"
#start powershell "..\bin\ref.exe  -c  D:/Projects/data/cfg_VTM4_0/encoder_randomaccess_vtm.cfg -c  D:/Projects/data/cfg_VTM4_0/per-sequence/BasketballPass.cfg -i D:/Projects/data/test_seq/HEVC/BasketballPass_416x240_50.yuv --PrintFrameMSE=1 -f 33 -q 37  -ip 48    | tee ./ref/ClassD_BasketballPass_416x240_50_37_RA.txt"
